# Generated by Django 3.0.1 on 2020-07-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
