# Generated by Django 3.0.1 on 2020-07-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addshg', '0002_loanregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanregister',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
